
-- Exercise 1

-- Q1) Create a database exercise
-- Q2) Create a table manufacturers as per the schema depicted
-- Q3) Create a table products as per the schema depicted
-- Q4) Add records to the table manufacturers
-- Q5) Add records to the table products
-- Q6) Display the names of all the products in the store.
-- Q7) Display the names and the prices of all the products in the store.
-- Q8) Display the name of the products with a price less than or equal to $200.
-- Q9) Dsiplay all the products with a price between $60 and $120.
-- Q10) Display avg price of all the products
-- Q11) Compute the average price of all products with manufacturer code equal to 2.
-- Q12) Compute the number of products with a price larger than or equal to $180 and set the column name as Prod_Count
-- Q13) Select the name and price of all products with a price larger than or equal to $180, 
--      and sort by price (in descending order)
-- Q14) Display the average price of each manufacturer's products, showing only the manufacturer's code.
-- Q15) Add a new product: Loudspeakers, $70, manufacturer 2.
-- Q16) Update the name of product 8 to "Laser Printer".
-- Q17) Update the products table and set discount to 10% on all products
-- Q18) Delete the record where Product code is 11
